# FROM node:16-alpine
# WORKDIR '/app'
# COPY ./package.json ./
# RUN npm i
# COPY . .
# CMD ["npm", "start"]

FROM node:16-alpine
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json .
RUN npm i
COPY --chown=node:node . .

CMD ["npm", "start"]
