# FROM node:16-alpine
# ENV CI=true
# WORKDIR '/app'
# COPY ./package.json ./
# RUN npm i
# COPY . .
# CMD ["npm", "start"]

FROM node:16-alpine
USER node
ENV CI=true

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json .
RUN npm i
COPY --chown=node:node . .

CMD ["npm", "start"]
