sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # Decrpyt Google Cloud service account credential file
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Install Google CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install Kubectl
  - gcloud components update kubectl
  # Login & config Google Cloud
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-6051
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build temperary docker file to run test
  - docker build -t g051/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true g051/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
