apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guoyd-com-tls
spec:
  secretName: guoyd-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: guoyd.com
  dnsNames:
    - guoyd.com
    - www.guoyd.com
